name: Check Dependencies

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "23 3 * * 2"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-deny:
    name: Lint dependencies with cargo-deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Rust
        uses: greenbone/actions/setup-rust@v3
        with:
          rust-version: stable
      - name: Install cargo-deny
        run: cargo install --locked --version 0.19.6 cargo-deny
      - run: make lint-deps

  unused-dependencies:
    name: Check for unused dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Rust
        uses: greenbone/actions/setup-rust@v3
        with:
          rust-version: stable
      - name: Install cargo-machete
        run: cargo install --locked --version 0.7.0 cargo-machete
      - name: Check unused dependencies
        run: make check-unused-deps
